import 'dart:io';

void main() {
  final now = DateTime.now();
  final date =
      '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}';
  final seqRaw = Platform.environment['BUILD_SEQ'] ?? '01';
  final seqDigits = seqRaw.replaceAll(RegExp(r'[^0-9]'), '');
  final seq = seqDigits.isEmpty
      ? '01'
      : (int.tryParse(seqDigits) ?? 1).clamp(1, 99).toString().padLeft(2, '0');

  final file = File('lib/config/build_info.g.dart');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync('''// GENERATED CODE - DO NOT EDIT BY HAND.
// Regenerated by tool/generate_build_info.dart at build time.

const String kGeneratedBuildDate = '$date';
const String kGeneratedBuildSeq = '$seq';
''');
  stdout.writeln('Generated build info: ${date}_$seq');
}
